# 创建向量和矩阵

In [4]:
import numpy as np
# 创建向量
v = np.array([1, 2, 3, 4, 5])
# 创建矩阵
m = np.array([[1,1],
            [2,2],
            [3,3],
            [4, 5]])

In [5]:
v

array([1, 2, 3, 4, 5])

In [6]:
m

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 5]])

# 向量和矩阵的基本属性

In [11]:
# 向量的维度
print(f'向量v的维度：' ,v.shape)
# 矩阵的维度
print(f'矩阵m的维度：',m.shape)
# 矩阵的行数和列数
print(f'矩阵m的行数：', m.shape[0]) # 行数
print(f'矩阵m的列数：', m.shape[1]) # 列数

向量v的维度： (5,)
矩阵m的维度： (4, 2)
矩阵m的行数： 4
矩阵m的列数： 2


# 索引和切片

In [13]:
# 索引
print(f'向量v的第二个元素：', v[1])
print(f'矩阵m的第三行第一个元素：', m[2, 0])
# 切片
print(f'向量v的后三个元素：', v[-3:])
print(f'矩阵m左上角的2x2子矩阵：', m[0:2, 0:2])

向量v的第二个元素： 2
矩阵m的第三行第一个元素： 3
向量v的后三个元素： [3 4 5]
矩阵m左上角的2x2子矩阵： [[1 1]
 [2 2]]


# 向量和矩阵的运算

In [16]:
# 向量加法
v1 = np.array([1, 2, 3])
v2 = np.array([2, 3])
v3 = np.array([2, 3, 4])
#print(np.add(v1, v2)) #向量维度不同，会报错
print(f'向量v1和v3相加：',np.add(v1, v3))

# 矩阵乘法
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
print(f'矩阵m1和m3相乘：', np.dot(m1, m2))

向量v1和v3相加： [3 5 7]
矩阵m1和m3相乘： [[19 22]
 [43 50]]


# 线性代数的基本运算

In [18]:
import numpy as np

# 数量乘法示例
scalar = 5 # 一个标量
scalard_vector = scalar * v
print(f'向量v：', v)
print(f'向量v 乘以标量scalar：', scalard_vector)

向量v： [1 2 3 4 5]
向量v 乘以标量scalar： [ 5 10 15 20 25]


In [19]:
# 矩阵的转置
print(f'矩阵 m：', m)
transposed_matrix = m.T
print(f'矩阵m的转置：', transposed_matrix)

矩阵 m： [[1 1]
 [2 2]
 [3 3]
 [4 5]]
矩阵m的转置： [[1 2 3 4]
 [1 2 3 5]]


In [22]:
# 计算行列式
# m_determinant = np.linalg.det(m) # 不是方阵会报错
print(f'矩阵m1：', m1)
m1_determinant = np.linalg.det(m1)
print(f'矩阵m1的行列式计算：', m1_determinant)

矩阵m1： [[1 2]
 [3 4]]
矩阵m1的行列式计算： -2.0000000000000004


In [24]:
# 求解线性方程组
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
result = np.linalg.solve(A, b)
print(f'线性方程组的求解：', result)

线性方程组的求解： [2. 3.]


# 计算逆矩阵

In [ ]:
import numpy as np

# 求线性方程(组)的数值解

## 有以下的方程组

$
\begin{aligned}
	&10x-y-2z=72,\\
	&-x+10y-2z=83,\\
    &-x-y+5z=42.
\end{aligned}
$

In [25]:
a = np.array([[10, -1, -2], [-1, 10, -2], [-1, -1, 5]])
b = np.array([[72], [83], [42]])
c = np.linalg.solve(a, b)
print(c)

[[11.]
 [12.]
 [13.]]


## 此外，还可以使用矩阵的逆来求解方程组

In [26]:
x = np.linalg.inv(a).dot(b)
print(x)

[[11.]
 [12.]
 [13.]]


## 利用 Sympy 求方程组的解析解

In [27]:
from sympy import symbols, solve, nonlinsolve

x, y = symbols('x y')
print(solve(x * 2 - 2, x)) # 解方程 2x-2=0

[1]


In [28]:
print(solve([x + y - 35, x * 2 + y * 4 - 94], x, y))  # 解方程组x + y = 35, 2x + 4y = 94

{x: 23, y: 12}


In [29]:
print(solve(x**2 + x - 20, x))  # 解方程x^2 + x - 20 = 0

[-5, 4]


In [30]:
a, b, c, d = symbols('a b c d', real=True)
print(nonlinsolve([a**2 + a + b, a - b], [a, b]))  # 解非线性方程组a^2 + a + b = 0, a - b = 0

{(-2, -2), (0, 0)}
